import type { Product, Zone, OrderStatus } from '../shared/models.js';
import { statusLabels } from '../shared/models.js';
import { $, api, state, esc, money, page, field, area, select, check, checked, errorBox, onForm, value, toast, fail } from './ui.js';
import { orderBody, memoryLinks, type Order } from './customer.js';
interface Dashboard { metrics: { revenue: number; orders: number; average: number; pending: number }; topProducts: { name: string; units: number }[]; recent: { code: string; status: OrderStatus; total: number }[]; unsentEmails: { count: number }; services: { payment: boolean; email: boolean; storage: boolean; live: boolean } }
type Category = { id: string; name: string; slug: string; active: number };
type Coupon = { id: string; code: string; kind: string; value: number; starts_at: string; ends_at: string; minimum: number; usage_limit: number; per_user: number; active: number };
type Policy = { slug: string; title: string; body: string; published: number };
const run = (action: () => Promise<void>) => () => { action().catch(fail); };
export async function admin() {
  if (!state.user) { location.href = '/cuenta?next=admin'; return; }
  if (state.user.role === 'customer') { page('Acceso reservado.', '<p>Esta sección está disponible únicamente para el equipo de KUYARI.</p><a href="/cuenta">Volver a mi cuenta</a>'); return; }
  const isAdmin = state.user.role === 'admin';
  const tabs = [['dashboard', 'Resumen'], ['orders', 'Pedidos'], ['products', 'Productos'], ['customers', 'Clientes'], ['memories', 'Recuerdos'], ...(isAdmin ? [['categories', 'Categorías'], ['zones', 'Entregas'], ['coupons', 'Cupones'], ['policies', 'Políticas'], ['users', 'Equipo'], ['audit', 'Actividad']] : [])];
  page('El taller de KUYARI.', `<p>Hola, ${esc(state.user.name)}. Aquí se preparan las próximas historias.</p><nav class="admin-tabs" aria-label="Administración">${tabs.map(([id, label]) => `<button type="button" data-tab="${id}" class="btn btn-outline">${label}</button>`).join('')}</nav>${errorBox}<div id="admin-content" aria-live="polite"></div>`, 'ADMINISTRACIÓN');
  const root = $('#admin-content');
  const formShell = (title: string, form: string) => `<h2>${esc(title)}</h2><form id="editor" class="admin-editor">${form}${errorBox}<button class="btn btn-primary" type="submit">Guardar</button><button class="btn btn-outline" type="button" id="cancel-edit">Volver</button></form>`;
  function back(tab: string) { $('#cancel-edit').onclick = run(() => load(tab)); }
  async function load(tab: string) {
    root.innerHTML = '<p role="status">Cargando…</p>';
    document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b => { b.setAttribute('aria-current', b.dataset.tab === tab ? 'page' : 'false'); });
    if (tab === 'dashboard') {
      const d = await api<Dashboard>('/api/admin/dashboard');
      root.innerHTML = `<div class="metrics"><div><span>Ventas aprobadas</span><strong>${money(d.metrics.revenue)}</strong></div><div><span>Pedidos</span><strong>${d.metrics.orders}</strong></div><div><span>Ticket promedio</span><strong>${money(d.metrics.average)}</strong></div><div><span>Por confirmar</span><strong>${d.metrics.pending}</strong></div></div><h2>Operación</h2><ul><li>Pagos: ${d.services.payment ? 'Configurados' : 'Pendientes de configurar'}</li><li>Correo: ${d.services.email ? 'Configurado' : 'Pendiente de configurar'}</li><li>Almacenamiento de producción: ${d.services.storage ? 'Configurado' : 'Pendiente de configurar'}</li><li>Tienda comercial: ${d.services.live ? 'Habilitada' : 'Cerrada al público'}</li><li>Correos en cola: ${d.unsentEmails.count}</li></ul>${isAdmin && d.unsentEmails.count ? '<button id="retry-emails" class="btn btn-outline">Reintentar correos pendientes</button>' : ''}<h2>Más vendidos</h2>${d.topProducts.length ? d.topProducts.map(p => `<p>${esc(p.name)} · ${p.units} unidades</p>`).join('') : '<p>Aún no hay ventas aprobadas.</p>'}<h2>Pedidos recientes</h2>${d.recent.map(o => `<p><button class="text-button" data-order="${esc(o.code)}">${esc(o.code)}</button> · ${esc(statusLabels[o.status])} · ${money(o.total)}</p>`).join('') || '<p>No hay pedidos todavía.</p>'}`;
      document.querySelectorAll<HTMLButtonElement>('[data-order]').forEach(b => b.onclick = run(() => editOrder(b.dataset.order!)));
      const retry = document.querySelector<HTMLButtonElement>('#retry-emails'); if (retry) retry.onclick = run(async () => { await api('/api/admin/email/retry', 'POST', {}); toast('Cola de correo habilitada para reintento'); });
    } else if (tab === 'orders') {
      root.innerHTML = `<h2>Pedidos</h2><form id="orders-search" class="catalog-tools">${field('q', 'Buscar código o correo', '', 'search', false)}${select('status', 'Estado', [{ value: '', label: 'Todos' }, ...Object.entries(statusLabels).map(([value, label]) => ({ value, label }))], '', false)}<button type="submit" class="btn btn-primary">Buscar</button></form><div id="orders-list"></div>`;
      async function search(q = '', status = '') { const rows = await api<{ code: string; status: OrderStatus; total: number; email: string }[]>(`/api/admin/orders?q=${encodeURIComponent(q)}&status=${status}`); $('#orders-list').innerHTML = `<div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Estado</th><th>Comprador</th><th>Total</th></tr></thead><tbody>${rows.map(o => `<tr><td><button class="text-button" data-order="${esc(o.code)}">${esc(o.code)}</button></td><td>${esc(statusLabels[o.status])}</td><td>${esc(o.email)}</td><td>${money(o.total)}</td></tr>`).join('')}</tbody></table></div>${!rows.length ? '<p>No hay pedidos con esos filtros.</p>' : ''}`; document.querySelectorAll<HTMLButtonElement>('[data-order]').forEach(b => b.onclick = run(() => editOrder(b.dataset.order!))); }
      onForm('#orders-search', async f => search(value(f, 'q'), value(f, 'status'))); await search();
    } else if (tab === 'products') {
      const rows = await api<Product[]>('/api/admin/products');
      root.innerHTML = `<h2>Tus productos, tus historias.</h2><div class="admin-intro"><div><h3>Sube lo que tienes disponible.</h3><p>Añade tus fotos, define el precio y el stock. Tus clientes podrán personalizarlo y pedirlo por WhatsApp.</p></div>${isAdmin ? '<button class="btn btn-primary" id="new-product">+ Subir nuevo producto</button>' : ''}</div>${isAdmin && rows.some(p => p.demo && p.active) ? '<div class="notice">Los productos marcados como muestra no representan inventario confirmado. <button class="text-button" id="hide-demo">Ocultar todos los productos de muestra</button></div>' : ''}<div class="admin-product-grid">${rows.map(p => `<article class="admin-product-card"><img src="${esc(p.images[0]?.url)}" alt="${esc(p.images[0]?.alt)}" loading="lazy" width="500" height="400"><div><p class="eyebrow">${p.active ? 'Visible en la tienda' : 'Oculto'}${p.demo ? ' · muestra' : ''}</p><h3>${esc(p.name)}</h3><p>${p.inquiryOnly ? 'Precio y disponibilidad por confirmar' : `${money(p.promo ?? p.price)} · ${p.stock} disponibles`}</p>${isAdmin ? `<button class="btn btn-outline" data-product="${esc(p.id)}">Editar producto</button>` : ''}</div></article>`).join('')}</div>`;
      if (isAdmin) { $('#new-product').onclick = run(() => editProduct()); document.querySelectorAll<HTMLButtonElement>('[data-product]').forEach(b => b.onclick = run(() => editProduct(rows.find(p => p.id === b.dataset.product)))); }
      const hide = document.querySelector<HTMLButtonElement>('#hide-demo'); if (hide) hide.onclick = run(async () => { await api('/api/admin/products/archive-demo', 'POST', {}); await load('products'); });
    } else if (tab === 'categories') {
      const rows = await api<Category[]>('/api/admin/categories');
      root.innerHTML = `<h2>Categorías</h2>${rows.map(c => `<p>${esc(c.name)} · ${c.active ? 'Activa' : 'Inactiva'} <button class="text-button" data-category="${esc(c.id)}">Editar</button></p>`).join('')}<form id="new-category" class="narrow">${field('name', 'Nombre de la categoría')}${field('slug', 'Nombre para la URL', '', 'text', true, 'pattern="[a-z0-9-]+"')}${errorBox}<button class="btn btn-primary" type="submit">Crear categoría</button></form>`;
      onForm('#new-category', async f => { await api('/api/admin/categories', 'POST', Object.fromEntries(new FormData(f))); await load(tab); });
      document.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b => b.onclick = () => { const c = rows.find(c => c.id === b.dataset.category)!; root.innerHTML = formShell('Editar categoría', `${field('name', 'Nombre', c.name)}${check('active', 'Activa', !!c.active)}`); back(tab); onForm('#editor', async f => { await api(`/api/admin/categories/${c.id}`, 'PATCH', { name: value(f, 'name'), active: checked(f, 'active') }); await load(tab); }); });
    } else if (tab === 'zones') {
      const rows = await api<Zone[]>('/api/admin/zones');
      root.innerHTML = `<h2>Zonas de entrega</h2><button id="new-zone" class="btn btn-primary">Añadir zona</button>${rows.map(z => `<p>${esc(z.district)} · ${esc(z.province)} · ${money(z.fee)} · ${z.active ? 'Activa' : 'Inactiva'} <button class="text-button" data-zone="${esc(z.id)}">Editar</button></p>`).join('')}`;
      const edit = (z?: Zone) => { root.innerHTML = formShell('Configurar entrega', `<div class="form-grid">${field('district', 'Distrito', z?.district)}${field('province', 'Provincia', z?.province)}${field('department', 'Departamento', z?.department)}${field('fee', 'Tarifa en soles', String((z?.fee ?? 0) / 100), 'number', true, 'min="0" step="0.01"')}${field('minDays', 'Días mínimos de preparación', String(z?.minDays ?? 1), 'number', true, 'min="1" max="30"')}</div>${area('slots', 'Horarios (uno por línea)', z?.slots.join('\n') ?? '09:00–12:00\n12:00–15:00')}${check('active', 'Zona activa', z ? !!z.active : true)}`); back(tab); onForm('#editor', async f => { await api(`/api/admin/zones${z ? `/${z.id}` : ''}`, z ? 'PUT' : 'POST', { district: value(f, 'district'), province: value(f, 'province'), department: value(f, 'department'), fee: cents(f, 'fee'), minDays: Number(value(f, 'minDays')), slots: lines(value(f, 'slots')), active: checked(f, 'active') }); await load(tab); }); };
      $('#new-zone').onclick = () => edit(); document.querySelectorAll<HTMLButtonElement>('[data-zone]').forEach(b => b.onclick = () => edit(rows.find(z => z.id === b.dataset.zone)));
    } else if (tab === 'coupons') {
      const rows = await api<Coupon[]>('/api/admin/coupons');
      root.innerHTML = `<h2>Cupones</h2><button id="new-coupon" class="btn btn-primary">Crear cupón</button>${rows.map(c => `<p>${esc(c.code)} · ${c.kind === 'percent' ? `${c.value}%` : money(c.value)} · ${c.active ? 'Activo' : 'Inactivo'} <button data-coupon="${esc(c.id)}" class="text-button">Editar</button></p>`).join('')}`;
      const edit = (c?: Coupon) => { root.innerHTML = formShell('Cupón de descuento', `<div class="form-grid">${field('code', 'Código', c?.code)}${select('kind', 'Tipo', [{ value: 'percent', label: 'Porcentaje' }, { value: 'fixed', label: 'Monto en soles' }], c?.kind ?? 'percent')}${field('value', 'Porcentaje o monto en soles', String(c ? c.kind === 'percent' ? c.value : c.value / 100 : 10), 'number', true, 'min="0.01" step="0.01"')}${field('minimum', 'Compra mínima en soles', String((c?.minimum ?? 0) / 100), 'number', true, 'min="0" step="0.01"')}${field('start', 'Fecha y hora de inicio (UTC)', c?.starts_at.slice(0, 16) ?? new Date().toISOString().slice(0, 16), 'datetime-local')}${field('end', 'Fecha y hora final (UTC)', c?.ends_at.slice(0, 16) ?? '', 'datetime-local')}${field('limit', 'Límite total de usos', String(c?.usage_limit ?? 100), 'number', true, 'min="1"')}${field('perUser', 'Usos por comprador', String(c?.per_user ?? 1), 'number', true, 'min="1"')}</div>${check('active', 'Activo', c ? !!c.active : true)}`); back(tab); onForm('#editor', async f => { await api(`/api/admin/coupons${c ? `/${c.id}` : ''}`, c ? 'PUT' : 'POST', { code: value(f, 'code'), kind: value(f, 'kind'), value: value(f, 'kind') === 'percent' ? Number(value(f, 'value')) : cents(f, 'value'), start: new Date(`${value(f, 'start')}Z`).toISOString(), end: new Date(`${value(f, 'end')}Z`).toISOString(), minimum: cents(f, 'minimum'), limit: Number(value(f, 'limit')), perUser: Number(value(f, 'perUser')), active: checked(f, 'active') }); await load(tab); }); };
      $('#new-coupon').onclick = () => edit(); document.querySelectorAll<HTMLButtonElement>('[data-coupon]').forEach(b => b.onclick = () => edit(rows.find(c => c.id === b.dataset.coupon)));
    } else if (tab === 'policies') {
      const rows = await api<Policy[]>('/api/admin/policies'); root.innerHTML = `<h2>Información legal y comercial</h2><p>Completa los datos reales y somete el contenido a revisión antes de publicarlo.</p>${rows.map(p => `<p>${esc(p.title)} · ${p.published ? 'Publicada' : 'Borrador'} <button class="text-button" data-policy="${esc(p.slug)}">Editar</button></p>`).join('')}`;
      document.querySelectorAll<HTMLButtonElement>('[data-policy]').forEach(b => b.onclick = () => { const p = rows.find(p => p.slug === b.dataset.policy)!; root.innerHTML = formShell('Editar política', `${field('title', 'Título', p.title)}${area('body', 'Contenido', p.body, 20000)}${check('published', 'Contenido revisado y aprobado para publicar', !!p.published)}`); back(tab); onForm('#editor', async f => { await api(`/api/admin/policies/${p.slug}`, 'PUT', { title: value(f, 'title'), body: value(f, 'body'), published: checked(f, 'published') }); await load(tab); }); });
    } else if (tab === 'customers') {
      const rows = await api<{ name: string; email: string; orders: number }[]>('/api/admin/customers'); root.innerHTML = `<h2>Clientes registrados</h2><div class="table-wrap"><table><thead><tr><th>Nombre</th><th>Correo</th><th>Pedidos</th></tr></thead><tbody>${rows.map(c => `<tr><td>${esc(c.name)}</td><td>${esc(c.email)}</td><td>${c.orders}</td></tr>`).join('')}</tbody></table></div><p>Los compradores invitados aparecen en el listado de pedidos.</p>`;
    } else if (tab === 'memories') { const rows = await api<{ token: string; privacy: string; active: number }[]>('/api/admin/memories'); root.innerHTML = `<h2>Recuerdos digitales</h2>${memoryLinks(rows) || '<p>Todavía no hay recuerdos.</p>'}`; }
    else if (tab === 'users') {
      const [staff, users] = await Promise.all([api<{ id: string; email: string; name: string; role: string; disabled: number }[]>('/api/admin/users'), api<{ id: string; email: string; name: string }[]>('/api/admin/customers')]);
      root.innerHTML = `<h2>Acceso del equipo</h2>${staff.map(u => `<p>${esc(u.name)} · ${esc(u.email)} · ${esc(u.role)} · ${u.disabled ? 'Deshabilitado' : 'Activo'}</p>`).join('')}<p>La persona debe crear primero su cuenta. Asigna solo el acceso que necesita.</p><form id="access-form" class="narrow">${select('id', 'Cuenta', users.filter(u => u.id !== state.user!.id).map(u => ({ value: u.id, label: `${u.name} · ${u.email}` })))}${select('role', 'Rol', [{ value: 'customer', label: 'Cliente' }, { value: 'operator', label: 'Operador de pedidos' }, { value: 'admin', label: 'Administrador' }])}${check('disabled', 'Deshabilitar cuenta')}${errorBox}<button type="submit" class="btn btn-primary">Actualizar acceso</button></form>`;
      onForm('#access-form', async f => { await api(`/api/admin/users/${value(f, 'id')}`, 'PATCH', { role: value(f, 'role'), disabled: checked(f, 'disabled') }); await load(tab); });
    } else if (tab === 'audit') { const rows = await api<{ action: string; resource: string; created_at: string }[]>('/api/admin/audit'); root.innerHTML = `<h2>Actividad administrativa</h2><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Acción</th><th>Referencia</th></tr></thead><tbody>${rows.map(r => `<tr><td>${esc(r.created_at)}</td><td>${esc(r.action)}</td><td>${esc(r.resource)}</td></tr>`).join('')}</tbody></table></div>`; }
  }
  async function editOrder(code: string) {
    const o = await api<Order>(`/api/admin/orders/${code}`);
    const next: Partial<Record<OrderStatus, OrderStatus>> = { pending_confirmation: 'confirmed', pending_payment: 'cancelled', paid: 'confirmed', confirmed: 'preparing', preparing: 'ready', ready: 'shipped', shipped: 'delivered' };
    root.innerHTML = `<h2>${esc(o.code)}</h2><button id="back-orders" class="btn btn-outline">Volver a pedidos</button>${orderBody(o, true)}${next[o.status] ? `<form id="status-form" class="narrow"><h3>Actualizar preparación</h3>${select('status', 'Siguiente estado', [{ value: next[o.status]!, label: statusLabels[next[o.status]!] }, ...(o.status === 'pending_confirmation' ? [{ value: 'cancelled', label: 'Cancelar solicitud' }] : [])])}${area('note', 'Nota interna')}${errorBox}<button class="btn btn-primary" type="submit">Actualizar estado</button></form>` : ''}<h2>Pagos verificados</h2>${o.payments?.map(p => `<p>${esc(p.provider_id)} · ${esc(p.status)} · ${money(p.amount)} · devuelto ${money(p.refunded)}</p>`).join('') || '<p>Aún no hay un pago verificado.</p>'}<form id="reconcile-form" class="narrow">${field('paymentId', 'ID del pago en Mercado Pago', '', 'text', true, 'pattern="[0-9]+"')}${errorBox}<button class="btn btn-outline" type="submit">Consultar y conciliar pago</button></form><p>Las devoluciones se tramitan en la cuenta del proveedor. Su resultado se verifica mediante notificación o conciliación.</p>`;
    $('#back-orders').onclick = run(() => load('orders'));
    if (next[o.status]) onForm('#status-form', async f => { await api(`/api/admin/orders/${code}`, 'PATCH', { status: value(f, 'status'), note: value(f, 'note') }); await editOrder(code); });
    onForm('#reconcile-form', async f => { await api(`/api/admin/payments/${value(f, 'paymentId')}/reconcile`, 'POST', {}); await editOrder(code); });
  }
  async function editProduct(p?: Product) {
    const categories = await api<Category[]>('/api/admin/categories');
    let images = p?.images.map(({ url, alt }) => ({ url, alt })) ?? [];
    const variants = [...(p?.variants ?? [])];
    root.innerHTML = formShell(p ? 'Editar regalo' : 'Crear un regalo', `<div class="form-grid">${field('name', 'Nombre del producto', p?.name)}${field('slug', 'Nombre para la URL', p?.slug, 'text', true, 'pattern="[a-z0-9-]+"')}${select('categoryId', 'Categoría', categories.map(c => ({ value: c.id, label: c.name })), p?.categoryId)}${field('price', 'Precio en soles', p?.inquiryOnly ? '' : String((p?.price ?? 0) / 100), 'number', true, 'min="0.01" step="0.01"')}${field('promo', 'Precio promocional (opcional)', p?.promo ? String(p.promo / 100) : '', 'number', false, 'min="0.01" step="0.01"')}${field('stock', 'Stock disponible (no incluye reservas)', String(p?.stock ?? 0), 'number', true, 'min="0" step="1"')}${field('memoryPrice', 'Complemento digital en soles', String((p?.memoryPrice ?? 0) / 100), 'number', true, 'min="0" step="0.01"')}</div>${field('summary', 'Descripción corta', p?.summary)}${area('description', 'Descripción completa', p?.description, 8000)}${check('inquiryOnly', 'Consultar precio y disponibilidad por WhatsApp', !!p?.inquiryOnly)}<p class="fine-print">Actívalo para mostrar una propuesta sin precio ni stock confirmado. Desactívalo y define ambos cuando puedas recibir pedidos desde el carrito.</p>${check('active', 'Visible en la tienda', !!p?.active)}${check('featured', 'Destacado', !!p?.featured)}${check('customizable', 'Permite personalización', p ? !!p.customizable : true)}<div class="form-grid">${area('styles', 'Estilos (uno por línea)', p?.options.styles.join('\n') ?? 'Clásico\nRomántico\nNatural')}${area('colors', 'Colores (uno por línea)', p?.options.colors.join('\n') ?? 'Coral\nRosa\nBlanco')}${area('occasions', 'Ocasiones (una por línea)', p?.options.occasions.join('\n') ?? 'Cumpleaños\nAniversario\nGracias\nPorque sí')}</div><h3>Imágenes</h3><div id="product-images"></div><label class="field">Añadir imagen<input type="file" id="product-upload" accept="image/jpeg,image/png,image/webp"></label><h3>Variantes</h3><div id="variant-list"></div><button id="add-variant" class="btn btn-outline" type="button">Añadir variante</button>`);
    back('products');
    const inquiryToggle = $<HTMLInputElement>('input[name=inquiryOnly]');
    const updatePricing = () => { for (const name of ['price', 'promo', 'stock']) { const input = $<HTMLInputElement>(`input[name=${name}]`); input.disabled = inquiryToggle.checked; input.required = !inquiryToggle.checked && name !== 'promo'; } };
    inquiryToggle.onchange = updatePricing; updatePricing();
    let uploading = false;
    const imageInput = $<HTMLInputElement>('#product-upload'); imageInput.multiple = true;
    imageInput.parentElement!.insertAdjacentHTML('beforebegin', '<p>Hasta 10 fotos por producto. JPG, PNG o WebP, máximo 3 MB cada una. La primera será la portada.</p><div id="photo-drop" class="photo-drop">Arrastra tus fotos aquí o selecciónalas abajo</div><p id="photo-status" role="status"></p>');
    function syncImages() { const f = $<HTMLFormElement>('#editor'); images.forEach((im, n) => { im.alt = value(f, `imageAlt${n}`) || im.alt; }); }
    function showImages() {
      $('#product-images').innerHTML = images.map((im, n) => `<div class="image-edit"><img src="${esc(im.url)}" alt="${esc(im.alt)}" width="100" height="100"><div>${n === 0 ? '<span class="eyebrow">Foto de portada</span>' : ''}${field(`imageAlt${n}`, 'Descripción de imagen', im.alt)}${n ? `<button type="button" data-cover="${n}" class="text-button">Usar como portada</button>` : ''}<button type="button" data-remove-image="${n}" class="text-button">Quitar</button></div></div>`).join('');
      document.querySelectorAll<HTMLButtonElement>('[data-remove-image]').forEach(b => b.onclick = () => { syncImages(); images = images.filter((_, n) => n !== Number(b.dataset.removeImage)); showImages(); });
      document.querySelectorAll<HTMLButtonElement>('[data-cover]').forEach(b => b.onclick = () => { syncImages(); const [cover] = images.splice(Number(b.dataset.cover), 1); images.unshift(cover); showImages(); });
    }
    function showVariants() { $('#variant-list').innerHTML = variants.map((v, n) => `<fieldset><legend>Variante ${n + 1}</legend><div class="form-grid">${field(`vlabel${n}`, 'Nombre', v.label)}${field(`vprice${n}`, 'Adicional en soles', String(v.priceDelta / 100), 'number', true, 'min="0" step="0.01"')}${field(`vstock${n}`, 'Stock disponible', String(v.stock), 'number', true, 'min="0"')}</div>${check(`vactive${n}`, 'Disponible', !!v.active)}</fieldset>`).join(''); }
    $('#add-variant').onclick = () => { const f = $<HTMLFormElement>('#editor'); variants.forEach((v, n) => { v.label = value(f, `vlabel${n}`); v.priceDelta = cents(f, `vprice${n}`); v.stock = Number(value(f, `vstock${n}`)); v.active = +checked(f, `vactive${n}`); }); variants.push({ id: '', label: '', priceDelta: 0, stock: 0, active: 1 }); showVariants(); };
    async function uploadPhotos(files: File[]) {
      if (uploading || !files.length) return;
      if (images.length + files.length > 10) { fail(new Error('Puedes añadir hasta 10 fotos por producto')); return; }
      if (files.some(file => file.size > 3 * 1024 * 1024)) { fail(new Error('Cada foto admite hasta 3 MB. Elige una imagen más pequeña.')); return; }
      uploading = true; imageInput.disabled = true; const submit = $<HTMLButtonElement>('#editor button[type=submit]'); submit.disabled = true;
      try { syncImages(); for (const [n, file] of files.entries()) {
        $('#photo-status').textContent = `Guardando foto ${n + 1} de ${files.length}…`;
        const body = new FormData(); body.set('file', file); const r = await api<{ url: string }>('/api/admin/images', 'POST', body);
        images.push({ url: r.url, alt: value($<HTMLFormElement>('#editor'), 'name') || 'Foto del producto' }); showImages();
      } $('#photo-status').textContent = `${images.length} fotos listas. Guarda el producto para publicarlas.`;
      } catch (e) { $('#photo-status').textContent = 'Las fotos ya cargadas se conservan. Puedes volver a intentar la que falta.'; fail(e); }
      finally { uploading = false; imageInput.disabled = false; imageInput.value = ''; submit.disabled = false; }
    }
    imageInput.onchange = () => { void uploadPhotos(Array.from(imageInput.files ?? [])); };
    $('#photo-drop').ondragover = e => { e.preventDefault(); };
    $('#photo-drop').ondrop = e => { e.preventDefault(); void uploadPhotos(Array.from(e.dataTransfer?.files ?? [])); };
    if (!p) {
      const f = $<HTMLFormElement>('#editor'), slug = f.elements.namedItem('slug') as HTMLInputElement;
      let edited = false; slug.oninput = () => { edited = true; };
      (f.elements.namedItem('name') as HTMLInputElement).oninput = () => { if (!edited) slug.value = value(f, 'name').normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); };
      (f.elements.namedItem('active') as HTMLInputElement).checked = true;
    }
    showImages(); showVariants();
    onForm('#editor', async f => {
      if (uploading) throw new Error('Espera a que terminen de subir tus fotos');
      if (!images.length) throw new Error('Añade al menos una foto de tu producto');
      const body = { name: value(f, 'name'), slug: value(f, 'slug'), categoryId: value(f, 'categoryId'), inquiryOnly: checked(f, 'inquiryOnly'), price: checked(f, 'inquiryOnly') ? 0 : cents(f, 'price'), promo: value(f, 'promo') ? cents(f, 'promo') : null, stock: Number(value(f, 'stock')), memoryPrice: cents(f, 'memoryPrice'), summary: value(f, 'summary'), description: value(f, 'description'), active: checked(f, 'active'), featured: checked(f, 'featured'), customizable: checked(f, 'customizable'), options: { styles: lines(value(f, 'styles')), colors: lines(value(f, 'colors')), occasions: lines(value(f, 'occasions')) }, images: images.map((im, n) => ({ ...im, alt: value(f, `imageAlt${n}`) })), variants: variants.map((v, n) => ({ id: v.id, label: value(f, `vlabel${n}`), priceDelta: cents(f, `vprice${n}`), stock: Number(value(f, `vstock${n}`)), active: checked(f, `vactive${n}`) })) };
      await api(`/api/admin/products${p ? `/${p.id}` : ''}`, p ? 'PUT' : 'POST', body); toast('Producto guardado'); await load('products');
    });
  }
  document.querySelectorAll<HTMLButtonElement>('[data-tab]').forEach(b => b.onclick = run(() => load(b.dataset.tab!)));
  await load('dashboard');
}
const cents = (f: HTMLFormElement, name: string) => Math.round(Number(value(f, name)) * 100);
const lines = (v: string) => v.split('\n').map(s => s.trim()).filter(Boolean);
