import { inquiryProduct } from './seasonal.js';
import { quickContact } from './contact.js';
import type { Product } from '../shared/models.js';
import { $, api, state, esc, money, card, page, field, select, errorBox, onForm, value, analytics, fail } from './ui.js';
interface Catalog { products: Product[]; total: number; page: number; pages: number }
export async function catalog(studio = false) {
  const query = new URLSearchParams(location.search);
  page(studio ? 'Empieza con un regalo.' : 'Regalos con intención.', `<p class="lead">${studio ? 'Elige el primer capítulo de tu sorpresa. Después lo haremos tuyo en KUYARI Studio.' : 'Flores, detalles y recuerdos que dicen lo que sientes.'}</p><form id="catalog-search" class="catalog-tools">${field('q', 'Buscar un regalo', query.get('q') ?? '', 'search', false)}${select('category', 'Categoría', [{ value: '', label: 'Todas' }, ...state.store!.categories.map(c => ({ value: c.id, label: c.name }))], query.get('category') ?? '', false)}${select('sort', 'Ordenar', [{ value: 'featured', label: 'Destacados' }, { value: 'popular', label: 'Más vendidos' }, { value: 'price_asc', label: 'Menor precio' }, { value: 'price_desc', label: 'Mayor precio' }], query.get('sort') ?? 'featured')}<button type="submit" class="btn btn-primary">Buscar</button></form><p id="catalog-count" role="status"></p><div class="product-grid" id="catalog-grid" aria-busy="true"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div><nav class="pagination" id="pagination" aria-label="Páginas del catálogo"></nav>${errorBox}`);
  async function search(params: URLSearchParams) {
    const data = await api<Catalog>(`/api/products?${params}`);
    $('#catalog-grid').innerHTML = data.products.length ? data.products.map(card).join('') : '<p class="empty-state">No encontramos regalos con esos filtros. Prueba otra búsqueda.</p>';
    $('#catalog-grid').setAttribute('aria-busy', 'false'); $('#catalog-count').textContent = `${data.total} regalos`;
    $('#pagination').innerHTML = `${data.page > 1 ? `<button class="btn btn-outline" data-page="${data.page - 1}">Anterior</button>` : ''}${data.pages > 1 ? `<span>Página ${data.page} de ${data.pages}</span>` : ''}${data.page < data.pages ? `<button class="btn btn-outline" data-page="${data.page + 1}">Siguiente</button>` : ''}`;
    $('#pagination').querySelectorAll<HTMLButtonElement>('[data-page]').forEach(b => b.onclick = () => { params.set('page', b.dataset.page!); search(params).catch(fail); });
  }
  onForm('#catalog-search', async f => { const p = new URLSearchParams({ q: value(f, 'q'), category: value(f, 'category'), sort: value(f, 'sort') }); history.replaceState(null, '', `/regalos?${p}`); analytics('search'); await search(p); });
  await search(query);
}
export async function product(slug: string) {
  const p = await api<Product>(`/api/products/${encodeURIComponent(slug)}`);
  analytics('view_item', { productId: p.id });
  if (p.inquiryOnly) { inquiryProduct(p); return; }
  page(p.name, `<a class="text-link" href="/regalos">← Todos los regalos</a><div class="product-detail"><div><img class="detail-photo" id="main-photo" src="${esc(p.images[0]?.url)}" alt="${esc(p.images[0]?.alt)}" width="800" height="800"><div class="thumbnails">${p.images.map((im, n) => `<button data-photo="${n}" aria-label="Ver imagen ${n + 1}"><img src="${esc(im.url)}" alt="${esc(im.alt)}" width="90" height="90"></button>`).join('')}</div></div><div class="detail-copy"><p class="eyebrow">${esc(p.category)}</p><p class="large-price">${p.promo ? `<del>${money(p.price)}</del> ` : ''}${money(p.promo ?? p.price)}</p><p class="preserve-lines">${esc(p.description)}</p><p>${p.stock ? `${p.stock} unidades disponibles` : 'Este regalo está agotado'}</p><p>Entrega según zona y tiempo de preparación. Verifica fecha y horario en el checkout.</p>${p.stock ? `<a class="btn btn-primary full-width" href="/studio?product=${esc(p.slug)}">${p.customizable ? 'Personalizar mi regalo' : 'Añadir a mi caja'}</a>` : '<a class="btn btn-outline" href="/regalos">Explorar otros regalos</a>'}${quickContact(p.name, money(p.promo ?? p.price))}<p class="fine-print">Tu configuración se guarda con el pedido para que el equipo prepare cada detalle.</p></div></div><section class="related"><h2>Otras formas de sorprender</h2><div class="product-grid" id="related"></div></section>`);
  document.querySelectorAll<HTMLButtonElement>('[data-photo]').forEach(b => b.onclick = () => { const im = p.images[Number(b.dataset.photo)]; const photo = $<HTMLImageElement>('#main-photo'); photo.src = im.url; photo.alt = im.alt; });
  const related = await api<Catalog>(`/api/products?category=${encodeURIComponent(p.categoryId)}`); $('#related').innerHTML = related.products.filter(v => v.id !== p.id).slice(0, 3).map(card).join('') || '<p>Esta colección seguirá creciendo.</p>';
}
export async function assistant() {
  const questions = [['recipient', '¿Para quién es?', ['Mi pareja', 'Una amistad', 'Mi familia', 'Alguien especial']], ['relationship', '¿Qué relación quieres celebrar?', ['Amor', 'Amistad', 'Familia', 'Agradecimiento']], ['occasion', '¿Cuál es la ocasión?', ['Cumpleaños', 'Aniversario', 'Gracias', 'Porque sí']], ['feeling', '¿Qué quieres transmitir?', ['Cariño', 'Alegría', 'Gratitud', 'Admiración']], ['style', '¿Qué estilo tiene?', ['Clásico', 'Romántico', 'Natural']]] as const;
  page('Tu Asistente Cómplice.', `<p class="lead">Cuéntanos un poco de esa persona. Te mostraremos opciones disponibles en nuestra colección.</p><form id="assistant-form" class="narrow">${questions.map(([name, label, options], n) => `<fieldset data-assistant-step="${n}" ${n ? 'hidden' : ''}><legend>${esc(label)}</legend>${select(name, 'Tu respuesta', options.map(v => ({ value: v, label: v })))}<button type="button" class="btn btn-primary" data-next="${n + 1}">Continuar</button></fieldset>`).join('')}<fieldset data-assistant-step="5" hidden><legend>¿Cuál es tu presupuesto máximo?</legend>${field('budget', 'Presupuesto en soles', '120', 'number', true, 'min="1" max="100000"')}<button class="btn btn-primary" type="submit">Encontrar mi sorpresa</button></fieldset>${errorBox}</form><div id="recommendations"></div>`);
  document.querySelectorAll<HTMLButtonElement>('[data-next]').forEach(b => b.onclick = () => { document.querySelectorAll<HTMLElement>('[data-assistant-step]').forEach(s => { s.hidden = s.dataset.assistantStep !== b.dataset.next; }); });
  onForm('#assistant-form', async f => {
    const data = await api<Catalog>(`/api/products?budget=${Math.round(Number(value(f, 'budget')) * 100)}`), occasion = value(f, 'occasion'), style = value(f, 'style');
    const recommended = data.products.filter(p => p.stock > 0).sort((a, b) => Number(b.options.occasions.includes(occasion)) + Number(b.options.styles.includes(style)) - Number(a.options.occasions.includes(occasion)) - Number(a.options.styles.includes(style))).slice(0, 3);
    $('#recommendations').innerHTML = `<h2>Un detalle para ${esc(value(f, 'recipient').toLowerCase())}</h2><p>Para expresar ${esc(value(f, 'feeling').toLowerCase())} y celebrar ${esc(value(f, 'relationship').toLowerCase())}. Opciones dentro de tu presupuesto; podrás personalizarlas con tu historia.</p><div class="product-grid">${recommended.length ? recommended.map(card).join('') : '<p>No hay regalos disponibles en ese presupuesto. Puedes ajustar el importe.</p>'}</div><a class="text-link" href="/asistente">Volver a empezar</a>`;
    analytics('assistant_recommendation', { count: recommended.length }); $('#recommendations').scrollIntoView({ behavior: 'smooth' });
  });
}
