import type { User, Customization, OrderStatus } from '../shared/models.js';
import { statusLabels } from '../shared/models.js';
import { $, api, state, esc, money, page, field, select, errorBox, onForm, value, toast, analytics, ApiError, fail } from './ui.js';
import { phoneLabel } from './contact.js';
export interface Order {
  channel: 'online' | 'whatsapp';
  id: string; code: string; status: OrderStatus; paymentStatus: string; subtotal: number; deliveryFee: number; discount: number; total: number; createdAt: string; expiresAt: number; email: string;
  buyer: { firstName: string; lastName: string; phone: string }; delivery: { recipient: string; phone: string; address: string; district: string; province: string; department: string; reference: string; date: string; slot: string; anonymous: boolean; instructions: string; secretMessage: string };
  items: { id: string; name: string; qty: number; unitPrice: number; customization: Customization }[];
  history: { status: OrderStatus; date: string }[]; memories: { token: string; privacy: string; active: number }[];
  payments?: { provider_id: string; status: string; amount: number; refunded: number }[];
  auditHistory?: { status: OrderStatus; note: string; created_at: string }[];
}
interface Account { user: User; orders: { code: string; status: OrderStatus; total: number; date: string }[]; addresses: { id: string; label: string; address: string; recipient: string; phone: string; zoneId: string }[]; memories: { token: string; active: number; privacy: string; code: string }[] }
const dateText = (iso: string) => new Date(iso).toLocaleString('es-PE', { timeZone: 'America/Lima', dateStyle: 'medium', timeStyle: 'short' });
export function memoryLinks(memories: { token: string; privacy: string; active: number }[]) { return memories.map((m, n) => `<div class="order-line"><div><a class="text-link" href="/recuerdo/${esc(m.token)}">Recuerdo ${n + 1} · ${esc(m.privacy)}</a><p>${m.active ? 'Disponible' : 'Inactivo o pendiente de pago'}</p></div><a href="/api/memories/${esc(m.token)}/qr" target="_blank" rel="noopener" class="btn btn-outline">Abrir QR</a></div>`).join(''); }
export function orderBody(o: Order, admin = false) {
  return `<div class="order-heading"><span class="status-pill">${esc(statusLabels[o.status])}</span><p>Creado el ${esc(dateText(o.createdAt))}</p></div><div class="checkout-layout"><div><ol class="timeline">${o.history.map(h => `<li><strong>${esc(statusLabels[h.status])}</strong><span>${esc(dateText(h.date))}</span></li>`).join('')}</ol><h2>Tu regalo</h2>${o.items.map(i => `<article class="order-detail-item"><h3>${esc(i.name)} × ${i.qty}</h3><p>${money(i.unitPrice * i.qty)}</p><p>${esc([i.customization.occasion, i.customization.style, i.customization.color].filter(Boolean).join(' · '))}</p>${i.customization.card ? `<blockquote class="dedication">${esc(i.customization.message)}</blockquote>` : '<p>Sin tarjeta</p>'}${i.customization.memory ? `<p>Recuerdo digital: ${esc(i.customization.privacy)}</p><p class="preserve-lines">${esc(i.customization.dedication)}</p><p>Remitente: ${esc(i.customization.sender)} · Destinatario: ${esc(i.customization.recipient)} · Fecha especial: ${esc(i.customization.specialDate)}</p>${i.customization.songUrl ? `<p><a href="${esc(i.customization.songUrl)}" rel="noopener noreferrer" target="_blank">Abrir canción</a></p>` : ''}${i.customization.videoUrl ? `<p><a href="${esc(i.customization.videoUrl)}" rel="noopener noreferrer" target="_blank">Abrir video</a></p>` : ''}${i.customization.assets.map((a, n) => `<a class="btn btn-outline" href="/api/assets/${esc(a)}" target="_blank" rel="noopener">Archivo ${n + 1}</a>`).join('')}` : ''}</article>`).join('')}<h2>Recuerdos digitales</h2>${o.memories.length ? memoryLinks(o.memories) : '<p>Este pedido no incluye recuerdo digital.</p>'}${admin && o.auditHistory ? `<h2>Historial interno</h2>${o.auditHistory.map(h => `<p>${esc(dateText(h.created_at))} · ${esc(statusLabels[h.status])} · ${esc(h.note)}</p>`).join('')}` : ''}</div><aside class="checkout-summary"><h2>Entrega</h2><p><strong>${esc(o.delivery.recipient)}</strong><br>${esc(o.delivery.address)}<br>${esc(o.delivery.district)} · ${esc(o.delivery.province)} · ${esc(o.delivery.department)}</p><p>${esc(o.delivery.date)} · ${esc(o.delivery.slot)}</p><p>Teléfono: ${esc(o.delivery.phone)}</p><p>${esc(o.delivery.reference)}</p><p>${o.delivery.anonymous ? 'Regalo anónimo' : 'Regalo con remitente'}</p>${o.delivery.instructions ? `<p>Instrucciones: ${esc(o.delivery.instructions)}</p>` : ''}${o.delivery.secretMessage ? `<p>Mensaje para el equipo: ${esc(o.delivery.secretMessage)}</p>` : ''}<h3>Comprador</h3><p>${esc(o.buyer.firstName)} ${esc(o.buyer.lastName)}<br>${esc(o.email)}<br>${esc(o.buyer.phone)}</p><dl class="totals"><div><dt>Productos</dt><dd>${money(o.subtotal)}</dd></div><div><dt>Entrega</dt><dd>${money(o.deliveryFee)}</dd></div><div><dt>Descuento</dt><dd>− ${money(o.discount)}</dd></div><div class="grand-total"><dt>Total</dt><dd>${money(o.total)}</dd></div></dl><p>Estado del pago: ${esc(o.paymentStatus === 'not_requested' ? 'Por coordinar en WhatsApp' : o.paymentStatus)}</p><div id="payment-action"></div></aside></div>`;
}
export async function order(code: string) {
  let o: Order;
  try { o = await api<Order>(`/api/orders/${encodeURIComponent(code)}`); }
  catch (e) { if (e instanceof ApiError && [401, 403, 404].includes(e.status)) return tracking(code); throw e; }
  page(`Tu pedido ${o.code}`, `<p class="lead">Tu sorpresa tiene una historia. Aquí puedes seguir cada paso.</p><div id="tracking-key"></div>${orderBody(o)}<div class="form-actions"><button class="btn btn-outline" id="refresh-order">Actualizar estado</button><a href="/regalos" class="text-link">Volver a la colección</a></div>${errorBox}`);
  const key = sessionStorage.getItem(`tracking:${o.code}`);
  if (key) {
    $('#tracking-key').innerHTML = `<div class="notice"><strong>Guarda tu clave de seguimiento</strong><p>Necesitarás esta clave y el código del pedido para consultarlo desde otro dispositivo. No la compartas públicamente.</p><code>${esc(key)}</code><button id="save-receipt" class="btn btn-outline">Descargar comprobante del pedido</button></div>`;
    $('#save-receipt').onclick = () => { const blob = new Blob([`KUYARI\nPedido: ${o.code}\nClave de seguimiento: ${key}\nSeguimiento: ${location.origin}/pedido/${o.code}\nTotal: ${money(o.total)}\nEstado al descargar: ${statusLabels[o.status]}\nEste resumen no es un comprobante tributario ni confirma un pago.\n`], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = `${o.code}.txt`; a.click(); URL.revokeObjectURL(url); };
  }
  if (o.status === 'pending_payment') {
    $('#payment-action').innerHTML = state.store!.paymentReady ? '<button id="pay-now" class="btn btn-primary full-width">Pagar con Mercado Pago</button><p class="fine-print">La reserva vence 30 minutos después de crear el pedido.</p>' : '<p class="notice">Pedido guardado, pendiente de pago. Los pagos online aún no están habilitados. No se ha realizado ningún cobro.</p>';
    const b = document.querySelector<HTMLButtonElement>('#pay-now'); if (b) b.onclick = async () => { b.disabled = true; try { const r = await api<{ url: string }>(`/api/orders/${o.code}/payment`, 'POST', {}); analytics('add_payment_info'); location.assign(r.url); } catch (e) { fail(e); b.disabled = false; } };
  }
  if (o.channel === 'whatsapp') {
    const w = await api<{ message: string; contacts: { label: string; phone: string; url: string }[] }>(`/api/orders/${o.code}/whatsapp`);
    $('#payment-action').innerHTML = `<div class="whatsapp-order"><h3>Ahora coordinemos tu sorpresa.</h3><p>Tu pedido ya está guardado. Envíanos el resumen a uno de estos números para confirmar disponibilidad y entrega.</p>${w.contacts.map((c, n) => `<a class="btn ${n ? 'btn-outline' : 'btn-whatsapp'} full-width" href="${esc(c.url)}" target="_blank" rel="noopener noreferrer"><span>Enviar pedido por WhatsApp<small>${phoneLabel(c.phone)}</small></span></a>`).join('')}<details><summary>Ver el mensaje que enviaré</summary><pre class="whatsapp-message">${esc(w.message)}</pre></details><p class="fine-print">No se ha realizado ningún cobro. Abrir WhatsApp no confirma automáticamente el pedido; KUYARI lo revisará contigo.</p></div>`;
  }
  if (o.paymentStatus === 'approved') { const key = `purchase:${o.code}`; if (!sessionStorage.getItem(key)) { analytics('purchase', { orderId: o.code, total: o.total }); sessionStorage.setItem(key, '1'); } }
  $('#refresh-order').onclick = () => { order(code).catch(fail); };
}
export function tracking(code = '') {
  page('Sigamos tu sorpresa.', `<p class="lead">Ingresa el código y la clave que recibiste al crear tu pedido. Si compraste con tu cuenta, también lo encontrarás en Mis pedidos.</p><form id="tracking-form" class="narrow">${field('code', 'Código del pedido', code, 'text', true, 'pattern="KU-[A-Fa-f0-9]{10}" autocomplete="off"')}${field('key', 'Clave de seguimiento', '', 'password', true, 'autocomplete="off"')}${errorBox}<button type="submit" class="btn btn-primary">Consultar pedido</button></form><a href="/cuenta" class="text-link">Ir a mi cuenta</a>`);
  onForm('#tracking-form', async f => { const code = value(f, 'code').toUpperCase(); await api('/api/orders/access', 'POST', { code, key: value(f, 'key') }); location.href = `/pedido/${code}`; });
}
export async function account() {
  if (!state.user) return login();
  const a = await api<Account>('/api/account');
  const loveLink = '<a class="btn btn-outline" href="/mis-cartas">Mis cartas y QR ♡</a>';
  page(`Hola, ${a.user.name}.`, `<div class="form-actions">${a.user.role !== 'customer' ? '<a href="/admin" class="btn btn-primary">Administrar KUYARI</a>' : ''}<button id="logout" class="btn btn-outline">Cerrar sesión</button></div><h2>Mis pedidos</h2>${a.orders.length ? `<div class="table-wrap"><table><thead><tr><th>Pedido</th><th>Estado</th><th>Total</th><th>Fecha</th></tr></thead><tbody>${a.orders.map(o => `<tr><td><a href="/pedido/${esc(o.code)}">${esc(o.code)}</a></td><td>${esc(statusLabels[o.status])}</td><td>${money(o.total)}</td><td>${esc(dateText(o.date))}</td></tr>`).join('')}</tbody></table></div>` : '<p>Aún no tienes pedidos asociados a tu cuenta.</p>'}<h2>Mis recuerdos</h2>${memoryLinks(a.memories) || '<p>Tus recuerdos aparecerán aquí.</p>'}<div class="form-grid account-sections"><section><h2>Mis datos</h2><form id="profile-form">${field('name', 'Nombre', a.user.name)}${errorBox}<button type="submit" class="btn btn-outline">Guardar nombre</button></form><p>Correo: ${esc(a.user.email)}</p><a href="/recuperar" class="text-link">Cambiar mi contraseña</a></section><section><h2>Mis direcciones</h2>${a.addresses.map(x => `<div class="order-line"><p><strong>${esc(x.label)}</strong><br>${esc(x.address)}</p><button class="text-button" data-delete-address="${esc(x.id)}">Eliminar</button></div>`).join('')}<form id="address-form">${field('label', 'Nombre de la dirección')}${field('recipient', 'Destinatario')}${field('phone', 'Teléfono', '', 'tel')}${field('address', 'Dirección', '', 'text', true, 'minlength="8"')}${select('zoneId', 'Zona', state.store!.zones.map(z => ({ value: z.id, label: `${z.district} · ${z.province}` })))}${errorBox}<button type="submit" class="btn btn-outline">Guardar dirección</button></form></section></div>`);
  $('#logout').onclick = async () => { try { await api('/api/auth/logout', 'POST', {}); location.reload(); } catch (e) { fail(e); } };
  document.querySelector('.form-actions')?.insertAdjacentHTML('beforeend', loveLink);
  onForm('#profile-form', async f => { await api('/api/account', 'PATCH', { name: value(f, 'name') }); toast('Nombre actualizado'); });
  onForm('#address-form', async f => { await api('/api/account/addresses', 'POST', Object.fromEntries(new FormData(f))); await account(); });
  document.querySelectorAll<HTMLButtonElement>('[data-delete-address]').forEach(b => b.onclick = async () => { try { await api(`/api/account/addresses/${b.dataset.deleteAddress}`, 'DELETE'); await account(); } catch (e) { fail(e); } });
}
export function login() {
  page('Tu lugar en KUYARI.', `<p class="lead">Guarda tus pedidos, direcciones y recuerdos en un solo lugar.</p><div class="form-grid auth-layout"><form id="login-form"><h2>Iniciar sesión</h2>${field('email', 'Correo electrónico', '', 'email', true, 'autocomplete="username"')}${field('password', 'Contraseña', '', 'password', true, 'minlength="12" maxlength="128" autocomplete="current-password"')}${errorBox}<button type="submit" class="btn btn-primary">Entrar</button><p><a href="/recuperar" class="text-link">Olvidé mi contraseña</a></p></form><form id="register-form"><h2>Crear mi cuenta</h2>${field('name', 'Nombre')}${field('email', 'Correo electrónico', '', 'email', true, 'autocomplete="email"')}${field('password', 'Contraseña (mínimo 12 caracteres)', '', 'password', true, 'minlength="12" maxlength="128" autocomplete="new-password"')}<label class="check-option"><input name="consent" type="checkbox" required>Acepto la <a href="/politicas/privacidad">política de privacidad</a>.</label>${errorBox}<button type="submit" class="btn btn-outline">Crear cuenta</button></form></div>`);
  onForm('#login-form', async f => { const r = await api<{ user: User; csrf: string }>('/api/auth/login', 'POST', { email: value(f, 'email'), password: value(f, 'password') }); state.user = r.user; state.csrf = r.csrf; location.href = new URLSearchParams(location.search).get('next') === 'admin' && r.user.role !== 'customer' ? '/admin' : '/cuenta'; });
  onForm('#register-form', async f => { await api('/api/auth/register', 'POST', { name: value(f, 'name'), email: value(f, 'email'), password: value(f, 'password'), consent: true }); location.href = '/cuenta'; });
}
export function recovery() {
  const resetToken = location.hash.slice(1); history.replaceState(null, '', '/recuperar');
  page('Recupera tu acceso.', `<form id="recovery-form" class="narrow">${resetToken ? field('password', 'Nueva contraseña', '', 'password', true, 'minlength="12" maxlength="128" autocomplete="new-password"') : field('email', 'Correo de tu cuenta', '', 'email')}${errorBox}<button class="btn btn-primary" type="submit">${resetToken ? 'Guardar contraseña' : 'Enviar enlace de recuperación'}</button><p id="recovery-result" role="status"></p></form><p><a href="/cuenta" class="text-link">Volver al inicio de sesión</a></p>`);
  onForm('#recovery-form', async f => { const r = await api<{ message: string }>(`/api/auth/${resetToken ? 'reset' : 'forgot'}`, 'POST', resetToken ? { token: resetToken, password: value(f, 'password') } : { email: value(f, 'email') }); $('#recovery-result').textContent = r.message; });
}
export function setup() {
  const setupToken = location.hash.slice(1); history.replaceState(null, '', '/activar-admin');
  if (!setupToken) { page('Activa tu taller.', '<p>Abre el enlace privado de activación incluido en la guía de entrega para crear tu primera cuenta administradora.</p><a class="btn btn-outline" href="/cuenta?next=admin">Ya tengo una cuenta</a>'); return; }
  page('Este es tu taller.', `<p class="lead">Crea tu acceso privado para subir las fotos de tus productos, actualizar precios y recibir tus pedidos. Este enlace funciona una sola vez.</p><form id="setup-form" class="narrow">${field('name', 'Tu nombre')}${field('email', 'Tu correo', '', 'email', true, 'autocomplete="email"')}${field('password', 'Elige una contraseña (mínimo 12 caracteres)', '', 'password', true, 'minlength="12" maxlength="128" autocomplete="new-password"')}${errorBox}<button class="btn btn-primary" type="submit">Activar mi panel KUYARI</button></form>`, 'BIENVENIDO A TU NEGOCIO');
  onForm('#setup-form', async f => { await api('/api/setup', 'POST', { name: value(f, 'name'), email: value(f, 'email'), password: value(f, 'password'), consent: true, setupToken }); location.href = '/admin'; });
}
export async function memory(publicToken: string) {
  interface MemoryData { dedication: string; message: string; sender: string; recipient: string; songUrl: string; videoUrl: string; specialDate: string; privacy: string; owner: boolean; active: boolean; assets: { id: string; mime: string }[] }
  let m: MemoryData;
  try { m = await api<MemoryData>(`/api/memories/${publicToken}`); }
  catch (e) {
    if (e instanceof ApiError && e.data.needsPin) { page('Una historia solo para ti.', `<p>Quien preparó esta sorpresa eligió protegerla con un PIN.</p><form id="pin-form" class="narrow">${field('pin', 'PIN del recuerdo', '', 'password', true, 'inputmode="numeric" pattern="[0-9]{6,12}"')}${errorBox}<button class="btn btn-primary" type="submit">Abrir mi recuerdo</button></form>`); onForm('#pin-form', async f => { await api(`/api/memories/${publicToken}/unlock`, 'POST', { pin: value(f, 'pin') }); await memory(publicToken); }); return; }
    throw e;
  }
  analytics('view_memory');
  page(m.recipient ? `Para ${m.recipient}.` : 'Hay una historia para ti.', `<div class="memory-experience">${!m.active ? '<p class="notice">Vista previa del propietario. Este recuerdo aún no está disponible para otras personas.</p>' : ''}<p class="eyebrow">${esc(m.specialDate)}</p><blockquote>${esc(m.message)}</blockquote><p class="preserve-lines memory-dedication">${esc(m.dedication)}</p><div class="memory-gallery">${m.assets.map(a => a.mime.startsWith('video/') ? `<video controls preload="metadata" src="/api/assets/${esc(a.id)}" aria-label="Video del recuerdo"></video>` : `<img loading="lazy" src="/api/assets/${esc(a.id)}" alt="Fotografía de este recuerdo">`).join('')}</div><div class="form-actions">${m.songUrl ? `<a class="btn btn-outline" href="${esc(m.songUrl)}" target="_blank" rel="noopener noreferrer">Escuchar nuestra canción ↗</a>` : ''}${m.videoUrl ? `<a class="btn btn-outline" href="${esc(m.videoUrl)}" target="_blank" rel="noopener noreferrer">Ver nuestro video ↗</a>` : ''}</div>${m.sender ? `<p class="signature">Con cariño, ${esc(m.sender)}</p>` : ''}${m.owner ? `<button id="memory-toggle" class="text-button">${m.active ? 'Desactivar el enlace de este recuerdo' : 'Activar este recuerdo'}</button>` : ''}</div>`, 'RECUERDO DIGITAL KUYARI');
  if (m.owner) $('#memory-toggle').onclick = async () => { try { await api(`/api/memories/${publicToken}`, 'PATCH', { active: !m.active }); await memory(publicToken); } catch (e) { fail(e); } };
}
export async function policy(slug: string) { const p = await api<{ title: string; body: string; published: number }>(`/api/policies/${encodeURIComponent(slug)}`); page(p.title, `<article class="policy-copy">${!p.published ? '<p class="notice">Borrador pendiente de revisión y aprobación antes del lanzamiento comercial.</p>' : ''}<div class="preserve-lines">${esc(p.body)}</div>${state.store!.businessEmail ? `<p>Contacto: <a href="mailto:${esc(state.store!.businessEmail)}">${esc(state.store!.businessEmail)}</a></p>` : ''}</article>`); }
