import {defaultInvitation,datePlans,datePlanLabel,peruToday,validReply,dateCalendarICS,type DateReply} from '../shared/invitation.js';
import type {LoveContent} from '../shared/romance.js';
import {esc} from './ui.js';
import type {LoveExperience} from './love-experience.js';
export interface InvitationOptions {reply?:DateReply|null;submit?:(reply:DateReply)=>Promise<DateReply>}
export function pixelPet(mascot='cat') {
 const head=mascot==='bunny'?'M28 45V5h15v32h34V5h15v40h7v37H85v16H35V82H21V45Z':mascot==='bear'?'M24 45V28h5v-5h15v5h5v9h22v-9h5v-5h15v5h5v17h4v37H85v16H35V82H20V45Z':'M24 46V22h8v6h7v6h7v4h28v-4h7v-6h7v-6h8v24h5v36H85v16H35V82H19V46Z';
 return `<svg class="date-pet pet-${mascot}" viewBox="0 0 120 112" role="img" aria-label="${mascot==='bear'?'Osito':mascot==='bunny'?'Conejito':'Gatito'} con un corazón" shape-rendering="crispEdges"><g class="date-pet-body" stroke="#543346" stroke-width="3"><path fill="${mascot==='bear'?'#eecbb0':'#fff9f5'}" d="${head}"/><path fill="#f3adbf" stroke="none" d="M32 ${mascot==='bunny'?9:32}h7v${mascot==='bunny'?22:9}h-7ZM81 ${mascot==='bunny'?9:32}h7v${mascot==='bunny'?22:9}h-7Z"/><path stroke="none" fill="#543346" d="M35 51h7v8h-7ZM78 51h7v8h-7Z"/><path stroke="none" fill="#e9a0b4" d="M27 62h15v6H27ZM78 62h15v6H78Z"/><path fill="none" d="M54 63l6 6 6-6M60 69v5l-5 4M60 74l5 4"/><path class="date-pixel-heart" stroke="none" fill="#cb507c" d="M41 80V73h12v6h14v-6h12v7h7v12h-7v7h-7v7H48v-7h-7v-7h-7V80Z"/></g><g class="date-pet-sparkles" fill="#c97597"><path d="M9 28h4v4H9ZM104 21h5v5h-5ZM8 90h5v5H8ZM106 80h4v4h-4Z"/></g></svg>`;
}
export function mountDateInvitation(root:HTMLElement,content:LoveContent,options:InvitationOptions={}):LoveExperience {
 let c=content,config=c.invitation||defaultInvitation(),step=options.reply?.status==='accepted'?3:options.reply?.status==='declined'?4:0;
 let selectedDate=options.reply?.date||'',time=options.reply?.time||config.preferredTime,plan=options.reply?.plan||'',saved=!!options.reply,saving=false,disposed=false;
 const today=peruToday(),base=new Date((selectedDate||today)+'T12:00:00Z');let month=base.getUTCMonth(),year=base.getUTCFullYear(),animation:Animation|undefined,dodges=0,paused=false;
 root.innerHTML=`<section class="date-world date-style-${config.style}"><div class="date-floating-hearts" aria-hidden="true">${Array.from({length:14},(_,i)=>`<span class="date-heart-${i%7}">${i%3?'♡':'✧'}</span>`).join('')}</div><button type="button" class="date-motion" aria-pressed="false">Pausar movimiento</button><div class="date-window"><div class="date-titlebar"><span data-date-filename></span><span aria-hidden="true">▣ ▢ ×</span></div><div class="date-screen"></div></div><p class="date-brand">KUYARI · pequeñas preguntas, grandes historias ♡</p></section>`;
 const world=root.querySelector<HTMLElement>('.date-world')!,screen=root.querySelector<HTMLElement>('.date-screen')!;
 const button=(label:string,action:string,secondary=false)=>`<button type="button" class="date-button${secondary?' date-button-secondary':''}" data-date-action="${action}">${label}</button>`;
 const pretty=(date:string)=>new Date(date+'T12:00:00Z').toLocaleDateString('es-PE',{weekday:'long',day:'numeric',month:'long',year:'numeric',timeZone:'America/Lima'});
 function render(focus=false){
  animation?.cancel();root.querySelector('[data-date-filename]')!.textContent=['una_pequeña_pregunta.exe','elige_nuestro_dia.cal','hagamos_planes.txt','es_una_cita.txt','a_tu_tiempo.txt'][step];
  let html='';
  if(step===0)html=`${pixelPet(config.mascot)}<p class="date-eyebrow">UNA PEQUEÑA PREGUNTA PARA ${esc(c.recipient||'TI')}</p><h2>${esc(config.question)}</h2><p class="date-message">${esc(c.message||'Me encantaría compartir un ratito contigo. ¿Hacemos un plan bonito?')}</p><div class="date-answer-buttons">${button(esc(config.yesLabel),'yes')}${button('Ahora no','no',true)}</div><p class="date-whisper">Sin presión. El gatito solo está un poquito ilusionado ♡</p>`;
  if(step===1){const firstDay=new Date(Date.UTC(year,month,1)),offset=(firstDay.getUTCDay()+6)%7,days=new Date(Date.UTC(year,month+1,0)).getUTCDate(),label=firstDay.toLocaleDateString('es-PE',{month:'long',year:'numeric',timeZone:'UTC'});
   html=`<p class="date-eyebrow">PASO 1 DE 2</p><h2>Elige nuestro día.</h2><p>Un huequito en tu calendario para una historia bonita.</p><label class="date-field">La fecha<input type="date" data-date-input min="${today}" max="${Number(today.slice(0,4))+2}${today.slice(4)}" value="${selectedDate}"></label><div class="date-calendar"><div class="date-month">${button('←','month-prev',true)}<strong>${esc(label)}</strong>${button('→','month-next',true)}</div><div class="date-calendar-grid"><span>L</span><span>M</span><span>M</span><span>J</span><span>V</span><span>S</span><span>D</span>${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const d=`${year}-${String(month+1).padStart(2,'0')}-${String(i+1).padStart(2,'0')}`;return `<button type="button" data-date-day="${d}" aria-label="${esc(pretty(d))}" aria-pressed="${selectedDate===d}" ${d<today||d>String(Number(today.slice(0,4))+2)+today.slice(4)?'disabled':''}>${i+1}</button>`;}).join('')}</div></div><label class="date-field">¿A qué hora? · hora de Perú<input type="time" data-date-time value="${time}"></label><p class="date-feedback" role="status"></p><div class="date-actions">${button('← Atrás','back',true)}${button('Continuar ♡','plans')}</div>`;
  }
  if(step===2)html=`<p class="date-eyebrow">PASO 2 DE 2</p><h2>¿Qué hacemos juntos?</h2><p>${esc(pretty(selectedDate))} · ${esc(time)}</p><div class="date-plan-grid">${config.plans.map(id=>{const p=datePlans.find(p=>p.id===id)!;return `<button type="button" data-date-plan="${id}" aria-pressed="${plan===id}"><span aria-hidden="true">${p.icon}</span><strong>${esc(datePlanLabel(config,id))}</strong><small>${esc(p.line)}</small></button>`;}).join('')}</div><p class="date-feedback" role="status"></p><div class="date-actions">${button('← Cambiar día','day',true)}${button(options.submit?'Confirmar mi respuesta ♡':'Ver nuestro ticket ♡','confirm')}</div>${!options.submit?'<p class="date-whisper">Vista previa: aquí puedes probar la invitación sin enviar una respuesta.</p>':'<p class="date-whisper">Al confirmar, quien creó la invitación podrá ver tu día, hora y plan.</p>'}`;
  if(step===3){const reply:DateReply={status:'accepted',date:selectedDate,time,plan};const message=`¡Sí, es una cita! ♡\n${c.recipient} y ${c.sender||'yo'}\n${pretty(selectedDate)} · ${time} (hora de Perú)\nPlan: ${datePlanLabel(config,plan)}\nLugar: ${config.venue||'Lo elegimos juntos'}`;const phone=config.replyPhone?(config.replyPhone.length===9?'51':'')+config.replyPhone:'';
   html=`${pixelPet(config.mascot)}<p class="date-eyebrow">${saved?'RESPUESTA GUARDADA':'NUESTRO PEQUEÑO PLAN'}</p><h2>¡Es una cita! ♡</h2><div class="date-ticket"><span class="date-ticket-label">UN RATITO CONTIGO</span><dl><dt>CUÁNDO</dt><dd>${esc(pretty(reply.date))}</dd><dt>HORA</dt><dd>${esc(reply.time)} · Perú</dd><dt>PLAN</dt><dd>${esc(datePlanLabel(config,reply.plan))}</dd><dt>DÓNDE</dt><dd>${esc(config.venue||'Lo elegimos juntos')}</dd><dt>QUIÉNES</dt><dd>${esc(c.recipient||'Tú')} + ${esc(c.sender||'yo')}</dd></dl><span class="date-ticket-barcode" aria-hidden="true">▌▎▌▏▎▌▌▏▌▎▌▏▎▌▌▎</span><small>VÁLIDO PARA HACER RECUERDOS BONITOS</small></div><p>${esc(config.successMessage)}</p><p class="date-whisper">${saved?'Tu respuesta está guardada para quien te invitó.':'Vista previa: no se ha enviado ninguna respuesta.'}</p><div class="date-actions">${button('Guardar en mi calendario','calendar')}${phone&&options.submit?`<a class="date-button date-button-secondary" href="https://wa.me/${phone}?text=${encodeURIComponent(message)}" target="_blank" rel="noopener noreferrer">Compartir por WhatsApp ↗</a>`:''}${button('Cambiar mi plan','day',true)}</div><p class="date-whisper">El ticket representa su plan; los lugares y reservas se coordinan entre ustedes.</p>`;
  }
  if(step===4)html=`${pixelPet(config.mascot)}<h2>A tu tiempo, con cariño.</h2><p>No pasa nada. Gracias por responder con sinceridad ♡</p><p class="date-whisper">${saved?'Tu respuesta se ha guardado.':'Vista previa: no se ha enviado una respuesta.'}</p><p class="date-feedback" role="status"></p>${button('Volver a la invitación','restart',true)}`;
  screen.innerHTML=html;world.classList.toggle('date-celebration',step===3);world.classList.toggle('date-waiting',step===0);
  if(!paused&&!matchMedia('(prefers-reduced-motion: reduce)').matches)animation=screen.animate([{opacity:.2,transform:'translateY(10px)'},{opacity:1,transform:'none'}],{duration:240,easing:'ease-out'});
  if(focus){root.scrollTop=0;const heading=screen.querySelector<HTMLElement>('h2')!;heading.tabIndex=-1;heading.focus({preventScroll:true});}
  bind();
 }
 function feedback(message:string){const el=screen.querySelector<HTMLElement>('.date-feedback');if(el)el.textContent=message;}
 async function submit(reply:DateReply){if(saving)return; saving=true;screen.querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.disabled=true);try{if(options.submit){await options.submit(reply);saved=true;}else saved=false;if(disposed)return;step=reply.status==='accepted'?3:4;render(true);}catch(e){if(disposed)return;render();feedback(e instanceof Error?e.message:'No se pudo guardar. Inténtalo nuevamente.');}finally{saving=false;}}
 function bind(){
  const no=screen.querySelector<HTMLButtonElement>('[data-date-action=no]');if(no)no.onpointerenter=e=>{if(!config.playfulNo||e.pointerType!=='mouse'||paused||matchMedia('(prefers-reduced-motion: reduce)').matches||dodges>=3)return;dodges++;no.style.transform=`translate(${dodges%2?-12:12}px,${dodges%2?9:-9}px)`;screen.querySelector<HTMLElement>('.date-whisper')!.textContent=['El gatito se puso nervioso ♡','Un poquito tímido…','Puedes elegir con toda libertad ♡'][dodges-1];};
  screen.querySelectorAll<HTMLButtonElement>('[data-date-action]').forEach(b=>b.onclick=()=>{const action=b.dataset.dateAction;
   if(action==='yes'){step=1;render(true);}if(action==='no'){step=4;render(true);void submit({status:'declined',date:'',time:'',plan:''});}
   if(action==='restart'){step=0;render(true);}if(action==='back'){step=0;render(true);}if(action==='day'){step=1;render(true);}
   if(action==='plans'){if(!validReply({status:'accepted',date:selectedDate,time,plan:config.plans[0]},config)){feedback('Elige una fecha válida desde hoy y una hora.');return;}step=2;render(true);}
   if(action==='confirm'){if(!validReply({status:'accepted',date:selectedDate,time,plan},config)){feedback('Elige el plan que más te guste y una fecha válida.');return;}void submit({status:'accepted',date:selectedDate,time,plan});}
   if(action==='month-prev'||action==='month-next'){const next=new Date(Date.UTC(year,month+(action==='month-next'?1:-1),1));if(next.toISOString().slice(0,7)<today.slice(0,7)||next.getUTCFullYear()>Number(today.slice(0,4))+2)return;month=next.getUTCMonth();year=next.getUTCFullYear();render();}
   if(action==='calendar'){const blob=new Blob([dateCalendarICS({status:'accepted',date:selectedDate,time,plan},config,c.recipient,c.sender)],{type:'text/calendar;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='KUYARI-nuestra-cita.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  });
  screen.querySelectorAll<HTMLButtonElement>('[data-date-day]').forEach(b=>b.onclick=()=>{selectedDate=b.dataset.dateDay!;render();});
  const dateInput=screen.querySelector<HTMLInputElement>('[data-date-input]');if(dateInput)dateInput.onchange=()=>{selectedDate=dateInput.value;if(dateInput.validity.valid&&selectedDate){const d=new Date(selectedDate+'T12:00:00Z');month=d.getUTCMonth();year=d.getUTCFullYear();render();}};
  const timeInput=screen.querySelector<HTMLInputElement>('[data-date-time]');if(timeInput)timeInput.oninput=()=>{time=timeInput.value;};
  screen.querySelectorAll<HTMLButtonElement>('[data-date-plan]').forEach(b=>b.onclick=()=>{plan=b.dataset.datePlan!;screen.querySelectorAll('[data-date-plan]').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));});
 }
 root.querySelector<HTMLButtonElement>('.date-motion')!.onclick=()=>{paused=!paused;world.classList.toggle('date-motion-paused',paused);const b=root.querySelector<HTMLButtonElement>('.date-motion')!;b.textContent=paused?'Volver a animar':'Pausar movimiento';b.setAttribute('aria-pressed',String(paused));};
 const visibility=()=>world.classList.toggle('date-inactive',document.hidden);document.addEventListener('visibilitychange',visibility);render();
 const dispose=(()=>{disposed=true;animation?.cancel();document.removeEventListener('visibilitychange',visibility);root.innerHTML='';}) as LoveExperience;
 dispose.update=(next)=>{if(disposed||next.theme!=='date-invite')return false;if(JSON.stringify([next.invitation,next.recipient,next.sender,next.message])===JSON.stringify([c.invitation,c.recipient,c.sender,c.message]))return true;c=next;config=c.invitation||defaultInvitation();if(root.querySelector('.date-world')&&!world.classList.contains('date-style-'+config.style))return false;render();return true;};return dispose;
}
