import type { LoveContent } from '../shared/romance.js';
import {esc} from './ui.js';
interface Asset {id:string;mime:string}
export interface BookScreen {name:string;html:string}
const safeURL=(url:string)=>{try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password;}catch{return false;}};
const initials=(name:string)=>name.trim().split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase()||'♡';
function photo(a:Asset|undefined,caption:string,name:string) {return a?.mime.startsWith('image/')?`<figure class="book-photo"><img src="/api/assets/${esc(a.id)}" alt="${esc(caption||'Un recuerdo de esta historia')}" loading="lazy" decoding="async"><figcaption>${esc(caption||'Un momento para siempre.')}</figcaption></figure>`:`<div class="book-monogram" aria-label="Iniciales de ${esc(name)}"><span>${esc(initials(name))}</span><small>UNA HISTORIA SOLO NUESTRA</small></div>`;}
export function bookCover(c:LoveContent,assets:Asset[]) {return `<span class="book-cover edition-${c.bookStyle}"><span class="book-cover-kicker">KUYARI · EDICIÓN ÚNICA</span><span class="book-cover-title">${esc(c.title)}</span>${assets.find(a=>a.mime.startsWith('image/'))?`<img class="book-cover-photo" src="/api/assets/${esc(assets.find(a=>a.mime.startsWith('image/'))!.id)}" alt="Un recuerdo en la portada">`:`<span class="book-cover-emblem" aria-hidden="true">${esc(initials(c.recipient))}</span>`}<span class="book-cover-quote">${esc(c.bookQuote||'De todas las historias, la nuestra.')}</span><span class="book-cover-name">PARA ${esc(c.recipient||'MI PERSONA FAVORITA')}</span></span>`;}
export function buildLoveBook(c:LoveContent,assets:Asset[],single=false):BookScreen[] {
  const date=c.specialDate ? new Date(`${c.specialDate}T12:00:00Z`).toLocaleDateString('es-PE',{day:'numeric',month:'long',year:'numeric',timeZone:'America/Lima'}) : '';
  const photos=assets.filter(a=>a.mime.startsWith('image/'));
  const videos=assets.filter(a=>a.mime.startsWith('video/'));
  const spreads:{name:string;left:string;right:string}[]=[];
  const text=(t:string)=>`<div class="book-prose">${esc(t)}</div>`;
  const over=(t:string)=>`<p class="book-kicker">${esc(t)}</p>`;
  const poster=`<div class="book-love-poster" aria-hidden="true"><span>LOVE</span><span>LOVE</span><span>LOVE</span><span>LOVE</span><small>${esc(c.bookQuote||'Nuestra historia merece quedarse.')}</small></div>`;
  spreads.push({name:'Dedicatoria',left:poster,right:`${over(c.occasion+(date?' · '+date:''))}<h2>${esc(c.title)}</h2><p class="book-byline">Para ${esc(c.recipient)}</p>${text(c.message)}${c.sender?`<p class="book-signature">${esc(c.sender)}</p>`:''}`});
  spreads.push({name:'Índice',left:'__BOOK_INDEX__',right:`${over('EL PROTAGONISTA DE ESTAS PÁGINAS')}<h2>${esc(c.recipient||'Mi persona favorita')}</h2>${photo(photos[0],c.bookCaptions[0]||c.bookQuote,c.recipient)}`});
  c.chapters.forEach((ch,i)=>spreads.push({name:ch.title,left:`${over('NUESTRO CAPÍTULO '+String(i+1).padStart(2,'0'))}<h2>${esc(ch.title)}</h2>${text(ch.text)}<span class="book-flourish">❦</span>`,right:`${photo(photos[(i+1)%Math.max(1,photos.length)],c.bookCaptions[(i+1)%Math.max(1,photos.length)]||ch.title,c.recipient)}<blockquote>${esc(c.bookQuote||'Lo bonito de esta historia es que es nuestra.')}</blockquote>`}));
  if(c.bookReasons.length){const items=(list:string[],start:number)=>`<ol class="book-reasons">${list.map((r,i)=>`<li><span>${String(start+i+1).padStart(2,'0')}</span>${esc(r)}</li>`).join('')}</ol>`;const half=Math.ceil(c.bookReasons.length/2);spreads.push({name:'Razones para elegirte',left:`${over('PEQUEÑOS DETALLES, UN AMOR ENORME')}<h2>Hay tantas<br>razones.</h2>${items(c.bookReasons.slice(0,half),0)}`,right:`${over('Y SIEMPRE ENCUENTRO UNA MÁS')}<h2>Volvería<br>a elegirte.</h2>${items(c.bookReasons.slice(half),half)}`});}
  for(let i=0;i<photos.length;i+=2)spreads.push({name:'Álbum '+(i/2+1),left:`${over('NUESTROS MOMENTOS')}${photo(photos[i],c.bookCaptions[i]||'Un instante nuestro.',c.recipient)}`,right:photos[i+1]?`${over('LO QUE QUIERO GUARDAR')}${photo(photos[i+1],c.bookCaptions[i+1]||'Un recuerdo para siempre.',c.recipient)}`:`${over('LOS RECUERDOS QUE VIENEN')}<h2>Todavía nos<br>quedan páginas.</h2><blockquote>${esc(c.bookQuote||'Lo más bonito aún lo estamos escribiendo.')}</blockquote><span class="book-flourish">♡</span>`});
  if(c.musicMode!=='off'||safeURL(c.songUrl)){spreads.push({name:'Nuestra canción',left:`${over('LA BANDA SONORA DE NOSOTROS')}<h2>Hay canciones<br>que son un abrazo.</h2><div class="book-record" aria-hidden="true"><span>KUYARI<br>♡</span></div>`,right:`${over('DALE PLAY A ESTE RECUERDO')}<h2>Nuestra<br>canción.</h2><blockquote>${esc(c.bookQuote||'Si suena nuestra canción, estoy un poquito más cerca.')}</blockquote>${c.musicMode!=='off'?'<button class="love-soft-button" type="button" data-book-music>Escuchar nuestra canción ♫</button>':''}${safeURL(c.songUrl)?`<a class="love-soft-button" href="${esc(c.songUrl)}" target="_blank" rel="noopener noreferrer">Abrir mi canción ↗</a>`:''}`});}
  if(c.bookMessages.length){const half=Math.ceil(c.bookMessages.length/2);const chat=(list:string[])=>`<div class="book-messages">${list.map((m,i)=>`<div class="book-message message-${i%2}"><span>CON CARIÑO</span><p>${esc(m)}</p><small>♡</small></div>`).join('')}</div>`;spreads.push({name:'Nuestros mensajes',left:`${over('PALABRAS QUE ME GUSTA GUARDAR')}<h2>Solo quería<br>recordártelo.</h2>${chat(c.bookMessages.slice(0,half))}`,right:`${over('UN MENSAJE Y UN POQUITO DE NOSOTROS')}<h2>Hay palabras<br>que abrazan.</h2>${chat(c.bookMessages.slice(half))}${photo(photos[1],c.bookCaptions[1]||'Mi persona favorita.',c.recipient)}`});}
  if(c.promises.length)spreads.push({name:'Lo que viene',left:`${over('LOS PLANES QUE QUIERO COMPARTIR')}<h2>Nos queda<br>una vida.</h2>${text(c.promises.join('\n\n'))}`,right:`${over('POR TODO LO QUE ESTÁ POR LLEGAR')}${poster}`});
  videos.forEach((a,i)=>spreads.push({name:'Nuestro video '+(i+1),left:`${over('UN RECUERDO EN MOVIMIENTO')}<h2>Volver a este<br>instante.</h2><blockquote>${esc(c.bookQuote)}</blockquote>`,right:`<video class="book-video" src="/api/assets/${esc(a.id)}" controls playsinline preload="none" aria-label="Video ${i+1} del libro"></video>`}));
  if(c.secretMessage)spreads.push({name:'Un secreto para ti',left:`${over('ENTRE TANTAS PÁGINAS')}<h2>Guardé algo<br>solo para ti.</h2><span class="book-flourish">♡</span>`,right:`${over('RASPA Y DESCUBRE')}<div class="love-scratch"><p class="love-secret" hidden>${esc(c.secretMessage)}</p><canvas width="640" height="280" aria-label="Raspa con tu dedo para descubrir el mensaje"></canvas></div><button class="love-soft-button" type="button" data-love-secret>Descubrir mi mensaje ♡</button>`});
  spreads.push({name:'Continuará',left:`${over('ESTO ES SOLO EL PRINCIPIO')}<div class="book-end">CONTINUARÁ<span>♡</span></div>`,right:`${over('POR NUESTRA HISTORIA')}<h2>${esc(c.closing)}</h2>${c.sender?`<p class="book-signature">${esc(c.sender)}</p>`:''}${safeURL(c.videoUrl)?`<a class="love-soft-button" href="${esc(c.videoUrl)}" target="_blank" rel="noopener noreferrer">Nuestro video ↗</a>`:''}<button type="button" class="love-soft-button" data-love-replay>Volver a sentirlo ↻</button>`});
  const contents=spreads.map((s,i)=>i===1?'':`<button type="button" data-book-jump="${i*(single?2:1)}"><span>${esc(s.name)}</span><b>${String(i*2+1).padStart(2,'0')}</b></button>`).join('');
  spreads[1].left=`${over('KUYARI · UN LIBRO PARA NOSOTROS')}<h2>Nuestro<br>índice.</h2><nav class="book-index" aria-label="Índice del libro">${contents}</nav>`;
  const page=(html:string,n:number)=>`<section class="book-page"><div class="book-page-content">${html}</div><footer><span>KUYARI · ${esc(c.recipient)}</span><span>${String(n).padStart(2,'0')}</span></footer></section>`;
  return spreads.flatMap((s,i)=>single?[{name:s.name,html:`<div class="book-spread book-single">${page(s.left,i*2+1)}</div>`},{name:s.name,html:`<div class="book-spread book-single">${page(s.right,i*2+2)}</div>`}]:[{name:s.name,html:`<div class="book-spread">${page(s.left,i*2+1)}${page(s.right,i*2+2)}</div>`}]);
}
