import { $, api, page, esc, field, area, check, checked, errorBox, onForm, value, money, toast } from './ui.js';
import { contactLinks } from './contact.js';
interface YapeSettings { enabled: boolean; phone: string; holder: string; qrUrl: string; instructions: string }
interface YapeOrder { settings: YapeSettings; eligible: boolean; amount: number; reports: { id: string; reference: string; payer: string; status: string; created_at: string }[] }
const reportStatus = (status: string) => status === 'approved' ? 'Pago verificado' : status === 'rejected' ? 'Reporte rechazado' : 'En revisión';
function paymentDetails(s: YapeSettings) {
  return `<div class="checkout-summary"><p class="eyebrow">YAPE · KUYARI</p><h2>Un detalle también empieza con confianza.</h2>${s.qrUrl ? `<img class="yape-qr" src="${esc(s.qrUrl)}" alt="QR real de la cuenta Yape de ${esc(s.holder)}" width="280" height="280">` : ''}${s.holder ? `<p>Titular: <strong>${esc(s.holder)}</strong></p>` : `<p>Comprueba el nombre del destinatario dentro de Yape antes de confirmar.</p>`}<p>Número de Yape: <strong>${esc(s.phone)}</strong></p><button type="button" class="btn btn-primary" id="copy-yape">Copiar número de Yape</button><ol><li>Abre Yape y busca este número${s.qrUrl ? ' o escanea el QR' : ''}.</li><li>Comprueba que el titular coincida y paga el importe confirmado por KUYARI.</li><li>Guarda el número de operación y reporta el pago.</li></ol>${s.instructions ? `<p class="preserve-lines">${esc(s.instructions)}</p>` : ''}<p class="fine-print">El pago se realiza en tu app Yape. KUYARI verifica la recepción antes de marcarlo como pagado.</p></div>`;
}
export async function yapePage() {
  const code = new URLSearchParams(location.search).get('pedido');
  const order = code ? await api<YapeOrder>('/api/orders/' + encodeURIComponent(code) + '/yape') : null;
  const settings = order?.settings || await api<YapeSettings>('/api/yape');
  if (!settings.enabled) { page('Pago con Yape.', '<p>Estamos verificando los datos de la cuenta receptora. Coordina tu pedido con KUYARI antes de hacer un pago.</p>' + contactLinks('Hola, KUYARI. Quiero confirmar mi pedido y los datos para pagar con Yape.')); return; }
  const review = order?.reports.find(r => r.status === 'review');
  page('Paga tu sorpresa con Yape.', `<p class="lead">Confirma primero tu regalo, el precio y la entrega. Después, paga desde Yape y guarda tu operación.</p><div class="checkout-layout">${paymentDetails(settings)}<section>${order ? `<h2>Pedido ${esc(code)}</h2><p>Importe del pedido: <strong>${money(order.amount)}</strong></p>${order.reports.map(r => `<p>${esc(reportStatus(r.status))} · Operación ${esc(r.reference)}</p>`).join('')}${order.eligible && !review ? `<form id="yape-report"><h3>Reportar mi pago</h3>${field('reference', 'Número de operación de tu pago Yape', '', 'text', true, 'minlength="4" maxlength="40" pattern="[A-Za-z0-9-]+" autocomplete="off"')}${field('payer', 'Nombre de quien realizó el pago', '', 'text', true, 'minlength="3" maxlength="120"')}${errorBox}<button type="submit" class="btn btn-primary">Enviar pago a revisión</button><p class="fine-print">Este reporte no confirma el pago. El equipo comprobará la operación en la cuenta receptora.</p></form>` : `<p>${review ? 'Tu operación está guardada y pendiente de verificación. Puedes consultar el estado de tu pedido.' : 'El equipo debe confirmar el pedido antes de registrar un pago; si ya está pagado, aquí verás su verificación.'}</p>`}<a class="btn btn-outline" href="/pedido/${esc(code)}">Ver mi pedido</a>` : `<h2>¿Ya coordinaste tu regalo?</h2><p>Si tienes un pedido guardado, entra a su seguimiento para reportar tu operación. Si lo coordinaste por WhatsApp, envía allí tu comprobante junto al detalle del regalo.</p><a class="btn btn-outline" href="/seguimiento">Abrir seguimiento del pedido</a><div class="form-actions">${contactLinks('Hola, KUYARI. Ya coordiné mi regalo y quiero enviar mi comprobante de Yape. Por favor verifiquen la recepción del pago.')}</div>`}</section></div>`);
  $('#copy-yape').onclick = async () => { try { await navigator.clipboard.writeText(settings.phone); toast('Número de Yape copiado'); } catch { toast('Número de Yape: ' + settings.phone); } };
  if (document.querySelector('#yape-report')) onForm('#yape-report', async f => { await api('/api/orders/' + encodeURIComponent(code!) + '/yape', 'POST', { reference: value(f, 'reference'), payer: value(f, 'payer') }); await yapePage(); toast('Operación guardada. El equipo verificará tu pago.'); });
}
export async function yapeAdmin(root: HTMLElement) {
  const [s, reports] = await Promise.all([api<YapeSettings>('/api/admin/yape'), api<{ id: string; code: string; reference: string; payer: string; amount: number; status: string; merchant: string }[]>('/api/admin/yape/reports')]);
  let qrUrl = s.qrUrl;
  root.innerHTML = `<h2>Yape · cobros y verificación</h2><p>Yape personal: verifica cada operación en la app antes de aprobarla. Los reportes del comprador quedan pendientes de revisión.</p><form id="yape-settings" class="admin-editor">${field('phone', 'Número real de Yape', s.phone, 'tel', true, 'pattern="9[0-9]{8}" maxlength="9"')}${field('holder', 'Titular tal como aparece en Yape', s.holder, 'text', false, 'maxlength="120"')}${area('instructions', 'Indicaciones adicionales (opcional)', s.instructions)}<label class="field">Subir tu QR real de Yape<input id="yape-qr-upload" type="file" accept="image/jpeg,image/png,image/webp"></label><div id="yape-qr-preview">${qrUrl ? `<img class="yape-qr" src="${esc(qrUrl)}" alt="QR de Yape" width="200" height="200">` : ''}</div><button type="button" class="text-button" id="yape-remove-qr">Quitar QR del cobro</button>${check('enabled', 'Mostrar Yape a los compradores', s.enabled)}${errorBox}<button type="submit" class="btn btn-primary">Guardar cuenta Yape</button></form><h2>Operaciones reportadas</h2>${reports.length ? reports.map(r => `<article class="order-line"><div><h3>${esc(r.code)} · ${money(r.amount)}</h3><p>Operación: ${esc(r.reference)} · ${esc(r.payer)}</p><p>Cuenta receptora al reportar: ${esc(JSON.parse(r.merchant).holder)} · ${esc(JSON.parse(r.merchant).phone)}</p><p>${esc(reportStatus(r.status))}</p>${r.status === 'review' ? `<form data-yape-review="${esc(r.id)}">${check('verified', 'He comprobado en Yape el titular, importe y número de operación')}${errorBox}<button type="submit" name="decision" value="approve" class="btn btn-primary">Confirmar recepción del pago</button><button type="submit" name="decision" value="reject" class="btn btn-outline">Rechazar reporte</button></form>` : ''}</div></article>`).join('') : '<p>No hay reportes de pago todavía.</p>'}`;
  const input = $<HTMLInputElement>('#yape-qr-upload');
  input.onchange = async () => { const file = input.files?.[0]; if (!file) return; const button = root.querySelector<HTMLButtonElement>('#yape-settings [type="submit"]')!; button.disabled = true; input.disabled = true;
    try { const data = new FormData(); data.set('file', file); const image = await api<{ url: string }>('/api/admin/images', 'POST', data); qrUrl = image.url; $('#yape-qr-preview').innerHTML = `<img class="yape-qr" src="${esc(qrUrl)}" alt="QR de Yape" width="200" height="200">`; } catch(e) { toast(e instanceof Error ? e.message : 'No pudimos subir el QR.'); } finally { button.disabled = false; input.disabled = false; input.value = ''; }
  };
  $('#yape-remove-qr').onclick = () => { qrUrl = ''; $('#yape-qr-preview').innerHTML = ''; };
  onForm('#yape-settings', async f => { await api('/api/admin/yape', 'PUT', { enabled: checked(f, 'enabled'), phone: value(f, 'phone'), holder: value(f, 'holder'), qrUrl, instructions: value(f, 'instructions') }); toast('Cuenta Yape guardada'); });
  root.querySelectorAll<HTMLFormElement>('[data-yape-review]').forEach(f => f.addEventListener('submit', async e => { e.preventDefault(); if (!checked(f, 'verified')) { toast('Comprueba primero la operación en tu app Yape.'); return; } const submitter = e.submitter as HTMLButtonElement; const buttons = f.querySelectorAll<HTMLButtonElement>('button'); buttons.forEach(b => b.disabled = true);
    try { await api('/api/admin/yape/reports/' + f.dataset.yapeReview + '/review', 'POST', { decision: submitter.value, verifiedInApp: true }); await yapeAdmin(root); toast(submitter.value === 'approve' ? 'Pago Yape verificado' : 'Reporte rechazado'); } catch(e) { toast(e instanceof Error ? e.message : 'No pudimos revisar el pago.'); buttons.forEach(b => b.disabled = false); }
  }));
}
