CREATE TABLE users (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'customer' CHECK(role IN ('customer','operator','admin')), disabled INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE TABLE sessions (id TEXT PRIMARY KEY, user_id TEXT REFERENCES users(id), csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX session_expiry ON sessions(expires_at);
CREATE TABLE password_resets (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at INTEGER NOT NULL);
CREATE TABLE addresses (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), data TEXT NOT NULL);
CREATE TABLE categories (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE products (id TEXT PRIMARY KEY, slug TEXT NOT NULL UNIQUE, name TEXT NOT NULL, summary TEXT NOT NULL, description TEXT NOT NULL, price INTEGER NOT NULL CHECK(price>0), promo INTEGER CHECK(promo>0 AND promo<price), stock INTEGER NOT NULL CHECK(stock>=0), category_id TEXT NOT NULL REFERENCES categories(id), active INTEGER NOT NULL, featured INTEGER NOT NULL, customizable INTEGER NOT NULL, memory_price INTEGER NOT NULL CHECK(memory_price>=0), options TEXT NOT NULL, demo INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX products_catalog ON products(active,category_id,price);
CREATE TABLE product_images (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), url TEXT NOT NULL, alt TEXT NOT NULL, position INTEGER NOT NULL);
CREATE INDEX images_product ON product_images(product_id);
CREATE TABLE product_variants (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), label TEXT NOT NULL, price_delta INTEGER NOT NULL CHECK(price_delta>=0), stock INTEGER NOT NULL CHECK(stock>=0), active INTEGER NOT NULL);
CREATE INDEX variants_product ON product_variants(product_id);
CREATE TABLE delivery_zones (id TEXT PRIMARY KEY, district TEXT NOT NULL, province TEXT NOT NULL, department TEXT NOT NULL, fee INTEGER NOT NULL CHECK(fee>=0), min_days INTEGER NOT NULL CHECK(min_days>=1), slots TEXT NOT NULL, active INTEGER NOT NULL);
CREATE TABLE coupons (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, kind TEXT NOT NULL CHECK(kind IN ('percent','fixed')), value INTEGER NOT NULL CHECK(value>0), starts_at TEXT NOT NULL, ends_at TEXT NOT NULL, minimum INTEGER NOT NULL, usage_limit INTEGER NOT NULL, per_user INTEGER NOT NULL, active INTEGER NOT NULL);
CREATE TABLE orders (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, session_id TEXT NOT NULL, user_id TEXT REFERENCES users(id), email TEXT NOT NULL, buyer TEXT NOT NULL, delivery TEXT NOT NULL, subtotal INTEGER NOT NULL, delivery_fee INTEGER NOT NULL, discount INTEGER NOT NULL, total INTEGER NOT NULL CHECK(total>0), status TEXT NOT NULL, payment_status TEXT NOT NULL DEFAULT 'pending', coupon_id TEXT REFERENCES coupons(id), reserved INTEGER NOT NULL DEFAULT 1, expires_at INTEGER NOT NULL, preference_id TEXT, checkout_url TEXT, payment_lock INTEGER NOT NULL DEFAULT 0, idempotency_key TEXT NOT NULL, request_hash TEXT NOT NULL, tracking_hash TEXT NOT NULL, policy_version TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(session_id,idempotency_key));
CREATE INDEX orders_account ON orders(user_id,created_at);
CREATE INDEX orders_status ON orders(status,created_at);
CREATE INDEX orders_expiry ON orders(status,expires_at);
CREATE TABLE session_orders (session_id TEXT NOT NULL, order_id TEXT NOT NULL REFERENCES orders(id), PRIMARY KEY(session_id,order_id));
CREATE TABLE order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), product_id TEXT NOT NULL REFERENCES products(id), variant_id TEXT REFERENCES product_variants(id), name TEXT NOT NULL, image TEXT NOT NULL, qty INTEGER NOT NULL CHECK(qty>0), unit_price INTEGER NOT NULL CHECK(unit_price>0), customization TEXT NOT NULL);
CREATE INDEX items_order ON order_items(order_id);
CREATE TABLE order_status_history (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), status TEXT NOT NULL, note TEXT NOT NULL, actor TEXT, created_at TEXT NOT NULL);
CREATE INDEX history_order ON order_status_history(order_id,created_at);
CREATE TABLE payments (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), provider TEXT NOT NULL, provider_id TEXT NOT NULL UNIQUE, status TEXT NOT NULL, amount INTEGER NOT NULL, refunded INTEGER NOT NULL DEFAULT 0, provider_updated TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX payments_order ON payments(order_id);
CREATE TABLE coupon_usages (id TEXT PRIMARY KEY, coupon_id TEXT NOT NULL REFERENCES coupons(id), order_id TEXT NOT NULL UNIQUE REFERENCES orders(id), identity_hash TEXT NOT NULL, status TEXT NOT NULL);
CREATE INDEX coupon_limits ON coupon_usages(coupon_id,identity_hash,status);
CREATE TABLE assets (id TEXT PRIMARY KEY, session_id TEXT NOT NULL, user_id TEXT REFERENCES users(id), storage_key TEXT NOT NULL, mime TEXT NOT NULL, size INTEGER NOT NULL, public_product INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL);
CREATE TABLE digital_memories (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), item_id TEXT NOT NULL UNIQUE REFERENCES order_items(id), public_token TEXT NOT NULL UNIQUE, privacy TEXT NOT NULL CHECK(privacy IN ('link','pin','private')), pin_hash TEXT, content TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 0);
CREATE INDEX memories_order ON digital_memories(order_id);
CREATE TABLE memory_assets (memory_id TEXT NOT NULL REFERENCES digital_memories(id), asset_id TEXT NOT NULL REFERENCES assets(id), PRIMARY KEY(memory_id,asset_id));
CREATE TABLE memory_access (session_id TEXT NOT NULL, memory_id TEXT NOT NULL REFERENCES digital_memories(id), expires_at INTEGER NOT NULL, PRIMARY KEY(session_id,memory_id));
CREATE TABLE outbox (id TEXT PRIMARY KEY, event_key TEXT NOT NULL UNIQUE, recipient TEXT NOT NULL, subject TEXT NOT NULL, body TEXT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, next_attempt INTEGER NOT NULL DEFAULT 0, sent_at TEXT);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, actor TEXT, action TEXT NOT NULL, resource TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE INDEX audit_date ON audit_logs(created_at);
CREATE TABLE policies (slug TEXT PRIMARY KEY, title TEXT NOT NULL, body TEXT NOT NULL, published INTEGER NOT NULL DEFAULT 0, updated_at TEXT NOT NULL);
