import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
let env = existsSync('.env') ? readFileSync('.env', 'utf8') : readFileSync('.env.example', 'utf8');
let token = env.match(/^SETUP_TOKEN=([A-Za-z0-9_-]{32,128})$/m)?.[1];
if (!token) {
  token = randomBytes(32).toString('base64url');
  env = /^SETUP_TOKEN=.*$/m.test(env) ? env.replace(/^SETUP_TOKEN=.*$/m, `SETUP_TOKEN=${token}`) : `${env}\nSETUP_TOKEN=${token}\n`;
  writeFileSync('.env', env, { mode: 0o600 });
}
writeFileSync('GUIA-PRIVADA.html', `<!doctype html><html lang="es"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Tu KUYARI está aquí</title><style>body{margin:0;background:#fcf5ef;color:#4c2138;font-family:system-ui,sans-serif;line-height:1.7}main{max-width:860px;margin:auto;padding:70px 28px}small{letter-spacing:3px}h1{font-family:Georgia,serif;font-size:clamp(44px,7vw,76px);line-height:1.05;font-weight:400}h2{font-family:Georgia,serif;font-size:30px}a{color:inherit}.actions{display:flex;flex-wrap:wrap;gap:14px;margin:32px 0}.button{padding:16px 26px;border-radius:50px;background:#5a183d;color:white;text-decoration:none}.secondary{background:#e9d9df;color:#4c2138}section{background:white;padding:28px;border-radius:22px;margin:20px 0}.note{font-size:14px;color:#745765}li{margin:12px 0}</style><main><small>KUYARI · TU NEGOCIO</small><h1>Tu historia,<br>lista para compartir.</h1><p>Tu tienda está lista para probarse en esta computadora. Sube las fotos de tus regalos y coordina cada pedido por WhatsApp.</p><div class="actions"><a class="button" href="http://localhost:3000">Ver mi tienda ↗</a><a class="button secondary" href="http://localhost:3000/activar-admin#${token}">Activar mi panel ↗</a><a class="button secondary" href="http://localhost:3000/admin">Ya tengo acceso</a></div><section><h2>Tus primeros productos</h2><ol><li>Activa tu panel con tu nombre, correo y una contraseña propia de al menos 12 caracteres.</li><li>En <b>Productos</b>, pulsa <b>Subir nuevo producto</b>. Añade hasta 10 fotos, elige la portada e indica precio y stock.</li><li>Guarda el producto. Aparecerá en la tienda y podrás editarlo cuando quieras.</li><li>Oculta las muestras desde el panel y configura tus zonas, tarifas y horarios en <b>Entregas</b>.</li></ol></section><section><h2>Una sorpresa, muchas maneras de hacerla tuya.</h2><p>Opciones de estilo y color, dedicatoria, ocasión, variantes, regalo anónimo, recuerdo digital con fotos, enlaces y QR, fecha y horario de entrega. El asistente ayuda a elegir según presupuesto.</p><p>Después de guardar el pedido, el cliente abre WhatsApp con su resumen y elige <b>+51 930 951 679</b> o <b>+51 900 080 962</b>. Tú revisas el pedido en el panel y confirmas la disponibilidad.</p></section><section><h2>Para volver a abrir KUYARI</h2><p>Ejecuta <b>ABRIR-KUYARI.cmd</b> dentro de esta carpeta. Tus productos, fotos y pedidos se conservan en <b>data</b>.</p><p>El catálogo inicial y la zona de entrega son de muestra. Aún falta alojamiento web para compartir un enlace público. Los pagos online están desactivados; no se cobra desde esta web.</p></section><p class="note">Guarda esta guía de forma privada: incluye el enlace para crear al primer administrador. Después de activar tu cuenta, el enlace no puede crear otro administrador. No hay correo de recuperación mientras no se configure SMTP.</p></main></html>`, { mode: 0o600 });
process.stdout.write('Guía privada lista. Abre GUIA-PRIVADA.html.\n');
